[build]
  command = "rm -rf ../cache/node_modules && npm install -no-cache && npm run build"
  functions = "json"

[[redirects]]
  from = "/api/*"
  to = "https://jsonmock.doselect.com/.netlify/functions/json/:splat"
  status = 200
  force = true