[build]
  command = "rm -rf ../cache/node_modules && npm install -no-cache && npm run build && ls -a ./ && cat ./node_modules/json-server/lib/server/defaults.js"
  functions = "json"

[[redirects]]
  from = "/api/*"
  to = "https://jsonmock.doselect.com/.netlify/functions/json/:splat"
  status = 200
  force = true